apiVersion: v1
kind: ResourceQuota
metadata:
  name: objects-quota
spec:
  hard:
    count/deployments.apps: 10
    count/replicasets.apps: 50
    count/statefulsets.apps: 5
    count/jobs.batch: 10
    count/cronjobs.batch: 3
    replicationcontrollers: 5
    pods: 100
    secrets: 10
    configmaps: 10
    persistentvolumeclaims: 50
    services: 10
    services.loadbalancers: 5
    services.nodeports: 5
    ssd.storageclass.storage.k8s.io/persistentvolumeclaims: 5

